SELECT
    N_NAME,
    COUNT(N_NATIONKEY) AS qtd
from
    NATION
    LEFT JOIN (
        SELECT
            C_NATIONKEY AS ORDERS_NATIONS
        FROM
            CUSTOMER
            LEFT JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY

) ON NATION.N_NATIONKEY = ORDERS_NATIONS
GROUP BY
    N_NATIONKEY
ORDER BY
    qtd DESC;