select
    COUNT(DISTINCT(C_CUSTKEY))
from
    CUSTOMER
    LEFT JOIN (
        SELECT DISTINCT(C_CUSTKEY) AS SPECIAL_KEY
        FROM
            CUSTOMER
            LEFT JOIN ORDERS ON ORDERS.O_CUSTKEY = CUSTOMER.C_CUSTKEY
        where
            C_COMMENT LIKE '%special request%'
) ON CUSTOMER.C_CUSTKEY = SPECIAL_KEY
WHERE SPECIAL_KEY IS NULL;